# One Hot Encoding

In [12]:
import numpy as np
import pandas as pd


In [4]:
datas = pd.read_csv("adult.csv",header=None)
datas

0   1       2            3   4                    5   \
0          NaN  C0      C2           C3  C4                   C5   
1          0.0  39   77516    Bachelors  13        Never-married   
2          1.0  50   83311    Bachelors  13   Married-civ-spouse   
3          2.0  38  215646      HS-grad   9             Divorced   
4          3.0  53  234721         11th   7   Married-civ-spouse   
...        ...  ..     ...          ...  ..                  ...   
32557  32556.0  27  257302   Assoc-acdm  12   Married-civ-spouse   
32558  32557.0  40  154374      HS-grad   9   Married-civ-spouse   
32559  32558.0  58  151910      HS-grad   9              Widowed   
32560  32559.0  22  201490      HS-grad   9        Never-married   
32561  32560.0  52  287927      HS-grad   9   Married-civ-spouse   

                       6               7       8        9   ...  \
0                      C6              C7      C8       C9  ...   
1            Adm-clerical   Not-in-family   White     Male  ...   
2         Exec-managerial         Husband   White     Male  ...   
3       Handlers-cleaners   Not-in-family   White     Male  ...   
4       Handlers-cleaners         Husband   Black     Male  ...   
...                   ...             ...     ...      ...  ...   
32557        Tech-support            Wife   White   Female  ...   
32558   Machine-op-inspct         Husband   White     Male  ...   
32559        Adm-clerical       Unmarried   White   Female  ...   
32560        Adm-clerical       Own-child   White     Male  ...   
32561     Exec-managerial            Wife   White   Female  ...   

                    15             16                17           18  \
0      C1_ Federal-gov  C1_ Local-gov  C1_ Never-worked  C1_ Private   
1                    0              0                 0            0   
2                    0              0                 0            0   
3                    0              0                 0            1   
4                    0              0                 0            1   
...                ...            ...               ...          ...   
32557                0              0                 0            1   
32558                0              0                 0            1   
32559                0              0                 0            1   
32560                0              0                 0            1   
32561                0              0                 0            0   

                     19                    20             21               22  \
0      C1_ Self-emp-inc  C1_ Self-emp-not-inc  C1_ State-gov  C1_ Without-pay   
1                     0                     0              1                0   
2                     0                     1              0                0   
3                     0                     0              0                0   
4                     0                     0              0                0   
...                 ...                   ...            ...              ...   
32557                 0                     0              0                0   
32558                 0                     0              0                0   
32559                 0                     0              0                0   
32560                 0                     0              0                0   
32561                 1                     0              0                0   

           23     24  
0      C14_-1  C14_1  
1           1      0  
2           1      0  
3           1      0  
4           1      0  
...       ...    ...  
32557       1      0  
32558       0      1  
32559       1      0  
32560       1      0  
32561       0      1  

[32562 rows x 25 columns]

In [14]:
new_data = pd.get_dummies(data=datas,columns=np.arange(1,14))
new_data

0              13     14               15             16  \
0          NaN             C13  C1_ ?  C1_ Federal-gov  C1_ Local-gov   
1          0.0   United-States      0                0              0   
2          1.0   United-States      0                0              0   
3          2.0   United-States      0                0              0   
4          3.0   United-States      0                0              0   
...        ...             ...    ...              ...            ...   
32557  32556.0   United-States      0                0              0   
32558  32557.0   United-States      0                0              0   
32559  32558.0   United-States      0                0              0   
32560  32559.0   United-States      0                0              0   
32561  32560.0   United-States      0                0              0   

                     17           18                19                    20  \
0      C1_ Never-worked  C1_ Private  C1_ Self-emp-inc  C1_ Self-emp-not-inc   
1                     0            0                 0                     0   
2                     0            0                 0                     1   
3                     0            1                 0                     0   
4                     0            1                 0                     0   
...                 ...          ...               ...                   ...   
32557                 0            1                 0                     0   
32558                 0            1                 0                     0   
32559                 0            1                 0                     0   
32560                 0            1                 0                     0   
32561                 0            0                 1                     0   

                  21  ...  12_90  12_91  12_92  12_94  12_95  12_96  12_97  \
0      C1_ State-gov  ...  False  False  False  False  False  False  False   
1                  1  ...  False  False  False  False  False  False  False   
2                  0  ...  False  False  False  False  False  False  False   
3                  0  ...  False  False  False  False  False  False  False   
4                  0  ...  False  False  False  False  False  False  False   
...              ...  ...    ...    ...    ...    ...    ...    ...    ...   
32557              0  ...  False  False  False  False  False  False  False   
32558              0  ...  False  False  False  False  False  False  False   
32559              0  ...  False  False  False  False  False  False  False   
32560              0  ...  False  False  False  False  False  False  False   
32561              0  ...  False  False  False  False  False  False  False   

       12_98  12_99  12_C12  
0      False  False    True  
1      False  False   False  
2      False  False   False  
3      False  False   False  
4      False  False   False  
...      ...    ...     ...  
32557  False  False   False  
32558  False  False   False  
32559  False  False   False  
32560  False  False   False  
32561  False  False   False  

[32562 rows x 22118 columns]

In [16]:
arr=np.arange(1,10)
np.delete(arr,np.where(arr==3))

array([1, 2, 4, 5, 6, 7, 8, 9])

# Standardization

In [17]:
import numpy as np
from sklearn.preprocessing import StandardScaler

In [36]:
data = np.random.rand(100,5)
print("Mean=",data.mean(axis=0))
print("Std=",data.std(axis=0))
data

Mean= [0.47898678 0.53121037 0.55483212 0.45570405 0.5057446 ]
Std= [0.27097761 0.31002476 0.28600496 0.28186215 0.27972931]


array([[4.19671066e-01, 6.44707292e-01, 6.73773180e-01, 6.83353496e-01,
        8.08820856e-01],
       [6.56440099e-01, 2.32073258e-01, 5.19085279e-02, 5.82111443e-01,
        3.96374586e-01],
       [2.56187626e-01, 4.51236108e-01, 8.62154121e-01, 4.90273637e-01,
        8.33126133e-01],
       [4.19026679e-02, 3.63528479e-01, 2.56620829e-01, 1.36008401e-01,
        9.01492638e-01],
       [8.54007988e-01, 5.42361717e-01, 5.67351762e-01, 1.47172705e-01,
        4.87168363e-01],
       [1.44820188e-01, 8.91136645e-02, 4.07940427e-01, 6.21917991e-01,
        5.12986835e-01],
       [7.23715409e-01, 5.06746162e-01, 7.09887112e-01, 7.93575826e-02,
        8.95145808e-01],
       [1.43322460e-02, 2.57414228e-01, 7.30456290e-01, 3.51842656e-01,
        8.07564034e-01],
       [4.38565176e-01, 8.60069954e-01, 4.40199670e-01, 2.30375339e-01,
        5.62455531e-01],
       [1.25861646e-01, 4.81681801e-01, 9.88311633e-01, 4.37225241e-01,
        2.27869903e-01],
       [5.83329659e-01, 9.7307

In [37]:
model = StandardScaler()
x_proccessed = model.fit_transform(X=data)
print("Mean=",x_proccessed.mean(axis=0))
print("Std=",x_proccessed.std(axis=0))
data

Mean= [-4.42978987e-16 -4.48183157e-16  5.08482145e-16  2.69229083e-16
 -1.35447209e-16]
Std= [1. 1. 1. 1. 1.]


array([[4.19671066e-01, 6.44707292e-01, 6.73773180e-01, 6.83353496e-01,
        8.08820856e-01],
       [6.56440099e-01, 2.32073258e-01, 5.19085279e-02, 5.82111443e-01,
        3.96374586e-01],
       [2.56187626e-01, 4.51236108e-01, 8.62154121e-01, 4.90273637e-01,
        8.33126133e-01],
       [4.19026679e-02, 3.63528479e-01, 2.56620829e-01, 1.36008401e-01,
        9.01492638e-01],
       [8.54007988e-01, 5.42361717e-01, 5.67351762e-01, 1.47172705e-01,
        4.87168363e-01],
       [1.44820188e-01, 8.91136645e-02, 4.07940427e-01, 6.21917991e-01,
        5.12986835e-01],
       [7.23715409e-01, 5.06746162e-01, 7.09887112e-01, 7.93575826e-02,
        8.95145808e-01],
       [1.43322460e-02, 2.57414228e-01, 7.30456290e-01, 3.51842656e-01,
        8.07564034e-01],
       [4.38565176e-01, 8.60069954e-01, 4.40199670e-01, 2.30375339e-01,
        5.62455531e-01],
       [1.25861646e-01, 4.81681801e-01, 9.88311633e-01, 4.37225241e-01,
        2.27869903e-01],
       [5.83329659e-01, 9.7307